# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Open Decoded
email: dev@decoded.com
description: > # this means to ignore newlines until "baseurl:"
  The home of Open-Source at Decoded!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://open.decoded.com" # the base hostname & protocol for your site
twitter_username: DecodedCo
github_username:  DecodedCo

# theme settings
paginate:     1
# Gems
gems:
  - jekyll-paginate

# Build settings
markdown: kramdown
